CREATE TABLE IF NOT EXISTS technologies.login
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    first_name character varying COLLATE pg_catalog."default" NOT NULL,
    last_name character varying COLLATE pg_catalog."default" NOT NULL,
    email_id character varying COLLATE pg_catalog."default",
    mobile_number character varying COLLATE pg_catalog."default" NOT NULL,
    password character varying COLLATE pg_catalog."default" NOT NULL,
    created_date timestamp without time zone NOT NULL,
    modified_date character varying COLLATE pg_catalog."default" NOT NULL
    )

    TABLESPACE pg_default;

ALTER TABLE IF EXISTS technologies.login
    OWNER to postgres;
-- Index: login_id_uindex

-- DROP INDEX IF EXISTS technologies.login_id_uindex;

CREATE UNIQUE INDEX IF NOT EXISTS login_id_uindex
    ON technologies.login USING btree
    (id ASC NULLS LAST)
    TABLESPACE pg_default;